// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtuoxtocgcbwlhriwyvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0dW94dG9jZ2Nid2xocml3eXZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NjY0ODksImV4cCI6MjA1ODU0MjQ4OX0.24aW6g2Q6WGih5vQ3llgL43ujhRsPflGClO2miuge3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);